name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: install
        run: yarn install --frozen-lockfile

      - name: build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: yarn build

      - name: deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
